export const TILES_CONFIG = [
    { name: 'START', type: 'special' },
    { name: 'Basic Firewall', type: 'firewall', price: 600 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'Encryption Suite', type: 'encryption', price: 800 },
    { name: 'Antivirus Pro', type: 'antivirus', price: 1000 },
    { name: 'Data Center EU', type: 'datacenter', price: 2000 },
    { name: 'Security Tax', type: 'tax' },
    { name: 'Network Shield', type: 'firewall', price: 1200 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'Jail', type: 'special' },
    { name: 'VPN Service', type: 'encryption', price: 1400 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'Cloud Security', type: 'antivirus', price: 1600 },
    { name: 'Data Center AS', type: 'datacenter', price: 2500 },
    { name: 'Malware Scanner', type: 'antivirus', price: 1800 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'Advanced IDS', type: 'firewall', price: 2000 },
    { name: 'Free Parking', type: 'special' },
    { name: 'Zero Trust', type: 'encryption', price: 2200 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'DDoS Protection', type: 'firewall', price: 2400 },
    { name: 'Data Center AP', type: 'datacenter', price: 3000 },
    { name: 'Blockchain Sec', type: 'encryption', price: 2600 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'AI Security', type: 'antivirus', price: 2800 },
    { name: 'Go to Jail', type: 'special' },
    { name: 'Quantum Crypto', type: 'encryption', price: 3000 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'Enterprise IPS', type: 'firewall', price: 3200 },
    { name: 'Data Center AF', type: 'datacenter', price: 3500 },
    { name: 'Security Tax', type: 'tax' },
    { name: 'Zero-Day Defense', type: 'antivirus', price: 3500 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'Ultimate Defense', type: 'firewall', price: 4000 },
    { name: 'Cyber Event', type: 'event' },
    { name: 'FINISH', type: 'special' }
]; 